/**
 * Определения предустановленных и пользовательских тем для калькулятора
 */

// Предустановленные темы
export const predefinedThemes = {
  light: {
    id: 'light',
    name: 'Светлая тема',
    variables: {
      '--bg-body': '#f5f5f5',
      '--bg-calculator': '#ffffff',
      '--bg-display': '#283747',
      '--color-display': '#ffffff',
      '--color-expression': '#aab7c4',
      '--color-memory': '#5dade2',
      '--bg-button': '#f0f0f0',
      '--bg-button-hover': '#e0e0e0',
      '--bg-button-active': '#d0d0d0',
      '--bg-button-operation': '#f39c12',
      '--bg-button-operation-hover': '#e67e22',
      '--bg-button-memory': '#3498db',
      '--bg-button-memory-hover': '#2980b9',
      '--bg-button-calculate': '#2ecc71',
      '--bg-button-calculate-hover': '#27ae60',
      '--bg-button-clear': '#e74c3c',
      '--bg-button-clear-hover': '#c0392b',
      '--bg-button-scientific': '#9b59b6',
      '--bg-button-scientific-hover': '#8e44ad',
      '--bg-history': '#ffffff',
      '--bg-history-header': '#34495e',
      '--color-history-header': '#ffffff',
      '--color-history-button': '#f39c12',
      '--color-history-button-hover': '#e67e22',
      '--bg-history-item-hover': '#f9f9f9',
      '--color-history-expression': '#7f8c8d',
      '--color-history-result': '#2c3e50',
      '--border-history-item': '#ecf0f1',
    },
  },

  dark: {
    id: 'dark',
    name: 'Темная тема',
    variables: {
      '--bg-body': '#1a1a1a',
      '--bg-calculator': '#2c2c2c',
      '--bg-display': '#1e1e1e',
      '--color-display': '#ffffff',
      '--color-expression': '#cccccc',
      '--color-memory': '#64b5f6',
      '--bg-button': '#404040',
      '--bg-button-hover': '#505050',
      '--bg-button-active': '#606060',
      '--bg-button-operation': '#ff9800',
      '--bg-button-operation-hover': '#f57c00',
      '--bg-button-memory': '#2196f3',
      '--bg-button-memory-hover': '#1976d2',
      '--bg-button-calculate': '#4caf50',
      '--bg-button-calculate-hover': '#388e3c',
      '--bg-button-clear': '#f44336',
      '--bg-button-clear-hover': '#d32f2f',
      '--bg-button-scientific': '#9c27b0',
      '--bg-button-scientific-hover': '#7b1fa2',
      '--bg-history': '#2c2c2c',
      '--bg-history-header': '#1e1e1e',
      '--color-history-header': '#ffffff',
      '--color-history-button': '#ff9800',
      '--color-history-button-hover': '#f57c00',
      '--bg-history-item-hover': '#383838',
      '--color-history-expression': '#aaaaaa',
      '--color-history-result': '#ffffff',
      '--border-history-item': '#404040',
    },
  },

  blue: {
    id: 'blue',
    name: 'Синяя тема',
    variables: {
      '--bg-body': '#e3f2fd',
      '--bg-calculator': '#ffffff',
      '--bg-display': '#1565c0',
      '--color-display': '#ffffff',
      '--color-expression': '#bbdefb',
      '--color-memory': '#81d4fa',
      '--bg-button': '#e3f2fd',
      '--bg-button-hover': '#bbdefb',
      '--bg-button-active': '#90caf9',
      '--bg-button-operation': '#2196f3',
      '--bg-button-operation-hover': '#1976d2',
      '--bg-button-memory': '#03a9f4',
      '--bg-button-memory-hover': '#0288d1',
      '--bg-button-calculate': '#4caf50',
      '--bg-button-calculate-hover': '#388e3c',
      '--bg-button-clear': '#f44336',
      '--bg-button-clear-hover': '#d32f2f',
      '--bg-button-scientific': '#673ab7',
      '--bg-button-scientific-hover': '#512da8',
      '--bg-history': '#ffffff',
      '--bg-history-header': '#1565c0',
      '--color-history-header': '#ffffff',
      '--color-history-button': '#2196f3',
      '--color-history-button-hover': '#1976d2',
      '--bg-history-item-hover': '#e3f2fd',
      '--color-history-expression': '#1976d2',
      '--color-history-result': '#0d47a1',
      '--border-history-item': '#e3f2fd',
    },
  },

  green: {
    id: 'green',
    name: 'Зеленая тема',
    variables: {
      '--bg-body': '#e8f5e8',
      '--bg-calculator': '#ffffff',
      '--bg-display': '#2e7d32',
      '--color-display': '#ffffff',
      '--color-expression': '#c8e6c9',
      '--color-memory': '#81c784',
      '--bg-button': '#e8f5e8',
      '--bg-button-hover': '#c8e6c9',
      '--bg-button-active': '#a5d6a7',
      '--bg-button-operation': '#4caf50',
      '--bg-button-operation-hover': '#388e3c',
      '--bg-button-memory': '#66bb6a',
      '--bg-button-memory-hover': '#4caf50',
      '--bg-button-calculate': '#2e7d32',
      '--bg-button-calculate-hover': '#1b5e20',
      '--bg-button-clear': '#f44336',
      '--bg-button-clear-hover': '#d32f2f',
      '--bg-button-scientific': '#7b1fa2',
      '--bg-button-scientific-hover': '#4a148c',
      '--bg-history': '#ffffff',
      '--bg-history-header': '#2e7d32',
      '--color-history-header': '#ffffff',
      '--color-history-button': '#4caf50',
      '--color-history-button-hover': '#388e3c',
      '--bg-history-item-hover': '#e8f5e8',
      '--color-history-expression': '#388e3c',
      '--color-history-result': '#1b5e20',
      '--border-history-item': '#e8f5e8',
    },
  },
};

// Шаблон для создания пользовательских тем
export const defaultCustomTheme = {
  id: '',
  name: 'Новая тема',
  isCustom: true,
  variables: {
    '--bg-body': '#f5f5f5',
    '--bg-calculator': '#ffffff',
    '--bg-display': '#283747',
    '--color-display': '#ffffff',
    '--color-expression': '#aab7c4',
    '--color-memory': '#5dade2',
    '--bg-button': '#f0f0f0',
    '--bg-button-hover': '#e0e0e0',
    '--bg-button-active': '#d0d0d0',
    '--bg-button-operation': '#f39c12',
    '--bg-button-operation-hover': '#e67e22',
    '--bg-button-memory': '#3498db',
    '--bg-button-memory-hover': '#2980b9',
    '--bg-button-calculate': '#2ecc71',
    '--bg-button-calculate-hover': '#27ae60',
    '--bg-button-clear': '#e74c3c',
    '--bg-button-clear-hover': '#c0392b',
    '--bg-button-scientific': '#9b59b6',
    '--bg-button-scientific-hover': '#8e44ad',
    '--bg-history': '#ffffff',
    '--bg-history-header': '#34495e',
    '--color-history-header': '#ffffff',
    '--color-history-button': '#f39c12',
    '--color-history-button-hover': '#e67e22',
    '--bg-history-item-hover': '#f9f9f9',
    '--color-history-expression': '#7f8c8d',
    '--color-history-result': '#2c3e50',
    '--border-history-item': '#ecf0f1',
  },
};
